server:
  servlet:
    session:
      timeout: 60m

  compression:
    enabled: true

  port: ${LOCAL_SERVER_PORT}

  tomcat:
    threads:
      max: 500
      min-spare: 50
    max-connections: 10000
    accept-count: 1000
    max-http-form-post-size: 50MB

spring:
  security:
    user:
      name: ${LOCAL_ADMIN_USER_ID}
      password: ${LOCAL_ADMIN_USER_PW}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    activate:
      on-profile: local
    include: env

  thymeleaf:
    cache: false

  devtools:
    livereload:
      enabled: true

    remote:
      restart:
        enabled: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  datasource:
    master:
      hikari:
        username: ${LOCAL_DB_MASTER_USERNAME}
        password: ${LOCAL_DB_MASTER_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://${LOCAL_DB_MASTER_IP}:${LOCAL_DB_MASTER_PORT}/${LOCAL_DB_MASTER_SCHEMA}?useUnicode=yes&characterEncoding=UTF-8
        pool-name: ${LOCAL_DB_MASTER_POOL}

    slave:
      hikari:
        username: ${LOCAL_DB_SLAVE_USERNAME}
        password: ${LOCAL_DB_SLAVE_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://${LOCAL_DB_SLAVE_IP}:${LOCAL_DB_SLAVE_PORT}/${LOCAL_DB_SLAVE_SCHEMA}?useUnicode=yes&characterEncoding=UTF-8
        pool-name: ${LOCAL_DB_SLAVE_POOL}

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      format_sql: true
      show_sql: true
      use_sql_comments: true
      ddl-auto: ${LOCAL_DDL_AUTO}
      use-new-id-generator-mappings: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: ${LOCAL_BATCH_SIZE}
          batch_versioned_data: true
        order_inserts: true
        order_updates: true

  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        max-wait: 1000
    port: ${LOCAL_REDIS_PORT}
    host: ${LOCAL_REDIS_HOST}
    connect-timeout: 100000
    timeout: 180000

springdoc:
  cache:
    disabled: true
  swagger-ui:
    path: swagger-ui-custom.html
  api-docs:
    path: /api-docs
  packages-to-scan: com.service.freeblog_admin


logging:
  pattern:
    console: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"
    file: "[%d] %-5level [${PID:-} - %thread - {%C => %M, %l}] %logger : %msg%n"

  file:
    name: ./logs/freeblog_admin.log
    max-history: 30

  level:
    root: INFO
    com.service: INFO

    org.hibernate:
#      SQL: debug
#      type.descriptor.sql: trace

mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

##### util config #####
util-config:
  # SFTP VM CONFIG
  # 저장 타입: images | videos
  aws_ec2_sftp:
    ip: ${LOCAL_AWS_EC2_SFTP_IP}
    port: ${LOCAL_AWS_EC2_SFTP_PORT}
    id: ${LOCAL_AWS_EC2_SFTP_ID}
    password: ${LOCAL_AWS_EC2_SFTP_PASSWORD}
    url: ${LOCAL_AWS_EC2_SFTP_URL}
    directory: ${LOCAL_AWS_EC2_SFTP_DIRECTORY}
    timeout: ${LOCAL_AWS_EC2_SFTP_TIMEOUT}
    protocol: ${LOCAL_AWS_EC2_SFTP_PROTOCOL}

  # AWS CONFIG
  aws_s3-bucket:
    access_key_id: ${LOCAL_AWS_S3_BUCKET_ACCESS_KEY_ID}
    secret_access_key_id: ${LOCAL_AWS_S3_BUCKET_SECRET_ACCESS_KEY_ID}
    bucket_name: ${LOCAL_AWS_S3_BUCKET_NAME}

  # SQL CONFIG
  sql_config:
    # FULL-TEXT | LIKE
    # TODO FULL-TEXT 검색은 아래 이슈 해결 전까지 사용 X
    # https://wwwnghks.tistory.com/100 (키워드에 +,- 포함 X)
    #  {org.mariadb.jdbc.util.log.Slf4JLogger => warn, %PARSER_ERROR[l]}] org.mariadb.jdbc.message.server.ErrorPacket :
    #  Error: 1064-42000: syntax error, unexpected $end, expecting FTS_TERM or FTS_NUMB or '*'
    #
    sql_search_pattern: LIKE

  admin_user:
    secret_key: ${LOCAL_ADMIN_USER_SECRET_KEY}
